apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 100Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mongo
  template:
    metadata:
      labels:
        db: mongo
    spec:
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
      - name: mongodb
        image: mongo:3.6
        resources:
          limits:
            memory: "8Gi"
            cpu: "2000m"
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-ip-service
spec:
  selector:
    db: mongo
  ports:
  - port: 27017
    targetPort: 27017
    