apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      amqp: rabbitmq
  template:
    metadata:
      labels:
        amqp: rabbitmq
    spec:
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        env:
          - name: RABBITMQ_DEFAULT_PASS
            value: "cenit_rabbit"
          - name: RABBITMQ_DEFAULT_USER
            value: "cenit_rabbit"
          - name: RABBITMQ_DEFAULT_VHOST
            value: "cenit_rabbit_vhost"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        volumeMounts:
          - name: rabbitmq-storage
            mountPath: /var/lib/rabbitmq
