apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      amqp: rabbitmq
  template:
    metadata:
      labels:
        amqp: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5672
        - containerPort: 15672
